### ISSUE TITLE
Failed building wheel for lz4

### ISSUE THREAD

**Issue by gerrymiller** [steeve/python-lz4#43]
Hi,

Trying to install on Windows but getting the following; any idea? Thank you very much for any help!

```
C:\Python34\Scripts>pip3 install lz4
Collecting lz4
  Downloading lz4-0.7.0.tar.gz
Building wheels for collected packages: lz4
  Running setup.py bdist_wheel for lz4
  Complete output from command C:\Python34\python.exe -c "import setuptools;__fi
le__='C:\\Users\\JENKIN~1.SER\\AppData\\Local\\Temp\\2\\pip-build-bj0wwmph\\lz4\
\setup.py';exec(compile(open(__file__).read().replace('\r\n', '\n'), __file__, '
exec'))" bdist_wheel -d C:\Users\JENKIN~1.SER\AppData\Local\Temp\2\tmphdjbyvorpi
p-wheel-:
  running bdist_wheel
  running build
  running build_ext
  building 'lz4' extension
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "C:\Users\JENKIN~1.SER\AppData\Local\Temp\2\pip-build-bj0wwmph\lz4\setu
p.py", line 42, in <module>
      'Programming Language :: Python :: 3.3',
    File "C:\Python34\lib\distutils\core.py", line 148, in setup
      dist.run_commands()
    File "C:\Python34\lib\distutils\dist.py", line 955, in run_commands
      self.run_command(cmd)
    File "C:\Python34\lib\distutils\dist.py", line 974, in run_command
      cmd_obj.run()
    File "C:\Python34\lib\site-packages\wheel\bdist_wheel.py", line 175, in run
      self.run_command('build')
    File "C:\Python34\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "C:\Python34\lib\distutils\dist.py", line 974, in run_command
      cmd_obj.run()
    File "C:\Python34\lib\distutils\command\build.py", line 126, in run
      self.run_command(cmd_name)
    File "C:\Python34\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "C:\Python34\lib\distutils\dist.py", line 974, in run_command
      cmd_obj.run()
    File "C:\Python34\lib\site-packages\setuptools-18.0.1-py3.4.egg\setuptools\c
ommand\build_ext.py", line 49, in run
    File "C:\Python34\lib\distutils\command\build_ext.py", line 339, in run
      self.build_extensions()
    File "C:\Python34\lib\distutils\command\build_ext.py", line 448, in build_ex
tensions
      self.build_extension(ext)
    File "C:\Python34\lib\site-packages\setuptools-18.0.1-py3.4.egg\setuptools\c
ommand\build_ext.py", line 174, in build_extension
    File "C:\Python34\lib\distutils\command\build_ext.py", line 503, in build_ex
tension
      depends=ext.depends)
    File "C:\Python34\lib\distutils\msvc9compiler.py", line 460, in compile
      self.initialize()
    File "C:\Python34\lib\distutils\msvc9compiler.py", line 371, in initialize
      vc_env = query_vcvarsall(VERSION, plat_spec)
    File "C:\Python34\lib\site-packages\setuptools-18.0.1-py3.4.egg\setuptools\m
svc9_support.py", line 52, in query_vcvarsall
    File "C:\Python34\lib\distutils\msvc9compiler.py", line 287, in query_vcvars
all
      raise ValueError(str(list(result.keys())))
  ValueError: ['path']

  ----------------------------------------
  Failed building wheel for lz4
Failed to build lz4
Installing collected packages: lz4
  Running setup.py install for lz4
    Complete output from command C:\Python34\python.exe -c "import setuptools, t
okenize;__file__='C:\\Users\\JENKIN~1.SER\\AppData\\Local\\Temp\\2\\pip-build-bj
0wwmph\\lz4\\setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).re
ad().replace('\r\n', '\n'), __file__, 'exec'))" install --record C:\Users\JENKIN
~1.SER\AppData\Local\Temp\2\pip-rxf1v3y6-record\install-record.txt --single-vers
ion-externally-managed --compile:
    running install
    running build
    running build_ext
    building 'lz4' extension
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\JENKIN~1.SER\AppData\Local\Temp\2\pip-build-bj0wwmph\lz4\se
tup.py", line 42, in <module>
        'Programming Language :: Python :: 3.3',
      File "C:\Python34\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "C:\Python34\lib\distutils\dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "C:\Python34\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "C:\Python34\lib\site-packages\setuptools-18.0.1-py3.4.egg\setuptools
\command\install.py", line 61, in run
      File "C:\Python34\lib\distutils\command\install.py", line 539, in run
        self.run_command('build')
      File "C:\Python34\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "C:\Python34\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "C:\Python34\lib\distutils\command\build.py", line 126, in run
        self.run_command(cmd_name)
      File "C:\Python34\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "C:\Python34\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "C:\Python34\lib\site-packages\setuptools-18.0.1-py3.4.egg\setuptools
\command\build_ext.py", line 49, in run
      File "C:\Python34\lib\distutils\command\build_ext.py", line 339, in run
        self.build_extensions()
      File "C:\Python34\lib\distutils\command\build_ext.py", line 448, in build_
extensions
        self.build_extension(ext)
      File "C:\Python34\lib\site-packages\setuptools-18.0.1-py3.4.egg\setuptools
\command\build_ext.py", line 174, in build_extension
      File "C:\Python34\lib\distutils\command\build_ext.py", line 503, in build_
extension
        depends=ext.depends)
      File "C:\Python34\lib\distutils\msvc9compiler.py", line 460, in compile
        self.initialize()
      File "C:\Python34\lib\distutils\msvc9compiler.py", line 371, in initialize

        vc_env = query_vcvarsall(VERSION, plat_spec)
      File "C:\Python34\lib\site-packages\setuptools-18.0.1-py3.4.egg\setuptools
\msvc9_support.py", line 52, in query_vcvarsall
      File "C:\Python34\lib\distutils\msvc9compiler.py", line 287, in query_vcva
rsall
        raise ValueError(str(list(result.keys())))
    ValueError: ['path']

    ----------------------------------------
Command "C:\Python34\python.exe -c "import setuptools, tokenize;__file__='C:\\Us
ers\\JENKIN~1.SER\\AppData\\Local\\Temp\\2\\pip-build-bj0wwmph\\lz4\\setup.py';e
xec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n
'), __file__, 'exec'))" install --record C:\Users\JENKIN~1.SER\AppData\Local\Tem
p\2\pip-rxf1v3y6-record\install-record.txt --single-version-externally-managed -
-compile" failed with error code 1 in C:\Users\JENKIN~1.SER\AppData\Local\Temp\2
\pip-build-bj0wwmph\lz4
```

**Comment by vahidpourmohamad** [comment]
same for me please help me

**Comment by darkdragn** [comment]
> same for me please help me

I haven't looked at this in a few years, but I'll see what I can do this evening.

**Comment by yemaedahrav** [comment]
Even I have been facing the same issue
