### ISSUE TITLE
Current lib version (1.1.0) non-functional (missing lz4.dumps)

### ISSUE THREAD

**Issue by rwarren** [steeve/python-lz4#54]
No `dumps` (or `compress`:)

```
$ pip install -U lz4
Collecting lz4
Requirement already up-to-date: future in /home/russ/miniconda3/envs/lz4/lib/python2.7/site-packages (from lz4)
Installing collected packages: lz4
Successfully installed lz4-1.1.0
$ python
Python 2.7.14 |Anaconda, Inc.| (default, Dec  7 2017, 17:05:42) 
[GCC 7.2.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import lz4
>>> lz4.dumps
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute 'dumps'
>>> lz4.compress
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute 'compress'
>>>
```

**Comment by rwarren** [comment]
wrong repo... sorry.
